language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
  - EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git#mirage-net-2.0.0"
  matrix:
  - OCAML_VERSION=4.04 PACKAGE=mirage-net-macosx
  - OCAML_VERSION=4.06 PACKAGE=mirage-net-macosx
os:
  - osx
